# Generated by Django 4.2.8 on 2023-12-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('passenger', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
